<form role="form" method="POST" action="<?= url_for('/admin/cadastrar/tipo-de-quarto');?>">
  <fieldset>
    <legend>Cadastro Tipo de Quarto</legend>
   <div class="form-group">
    <label for="typeroom[type]">Tipo</label>
    <input type="text" class="form-control" name="typeroom[type]" placeholder="">
  </div>

    
   <div class="form-group">
    <label for="typeroom[description]">Descrição</label>
    <textarea class="form-control" name="typeroom[description]"></textarea>
  </div>  
    <div class="form-group">
        <label for="typeroom[dailyValue]">Valor da Diária</label>
        <input type="text" class="form-control" name="typeroom[dailyValue]" placeholder="">

      </div>
  <button type="submit" class="btn btn-primary">Cadastrar</button>
</fieldset>
</form>
