<h3>Listagem de Reservas</h3>
<?php if(!empty($reserves)) {?>


<table class="table">
	<tr>
		<td>Quarto</td>		
		<td>Cliente</td>
		<td>Entrada</td>
		<td>Saída</td>
	</tr>
	
<?php foreach($reserves as $reserve) {?>
	<?php if($reserve->getVisible() == 't') {?>
	<tr>
		<td><?= $reserve->getRoom()->getNumberic() ?></td>		
		<td><?= $reserve->getClient()->getName() .' '. $reserve->getClient()->getSurname()?></td>
		<td><?= $reserve->getDataInput() ?></td>
		<td><?= $reserve->getDataOutput() ?></td>
		<td>
			<?= link_to("/admin/reservas/{$reserve->getId()}/detalhes", "Detalhes", "class='btn btn-primary'") ?>
			<?= link_to("/admin/reservas/{$reserve->getId()}/editar", "Editar", "class='btn btn-primary'") ?>
			<?= link_to("/admin/reservas/{$reserve->getId()}/cancelar", "Cancelar", "class='btn btn-primary'") ?>
			<?= link_to("#", "Confirmar Hospedagem", "class='btn btn-success'") ?>
		</td>
	</tr>
	<?php }?>
<?php }?>
	
</table>

<?php } else {?>
	<p>Não existem reservas atualmente</p>
<?php }?>
<?= link_to('/admin/reservas/nova', 'Nova Reserva', "class='btn btn-success'") ?>

