<section>
  <header>
      <h2>Hotel Campeão</h2>
  </header>

  <article class="col-md-4">
        <h4>Título</h4>
        <?php $style="style='width: 150px; heigth:140px;'" ;?>
        <?= add_image ('image.jpg','icons',$style) ?> 
        <p>hashdasdasdsadasdsadasdsadasdsakdnsfnsdfjndsjgndsgnsn
           gnghashdasdasdsadasdsadasdsadasdsakdnsfnsdfjndsjgndsg
           nsngngshashdasdasdsadasdsadasdsadasdsakdnsfnsdfjndsjg
           ndsgnsngngssdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfn
           dsfnsdsdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfndsfns
           sdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfndsfnsdfddds
           sdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfndsfnsdfddds
        </p>

        <a href="#" class="btn btn-primary">Butao-zinho</a>
    </article>


<article class="col-md-4">
        <h4>Título</h4>
        <?php $style="style='width: 150px; heigth:140px;'" ;?>
        <?= add_image ('image.jpg','icons',$style) ?> 
        <p>hashdasdasdsadasdsadasdsadasdsakdnsfnsdfjndsjgndsgnsn
           gnghashdasdasdsadasdsadasdsadasdsakdnsfnsdfjndsjgndsg
           nsngngshashdasdasdsadasdsadasdsadasdsakdnsfnsdfjndsjg
           ndsgnsngngssdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfn
           dsfnsdsdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfndsfns
           sdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfndsfnsdfddds
           sdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfndsfnsdfddds
        </p>

        <a href="#" class="btn btn-primary">Butao-zinho</a>
    </article>

<article class="col-md-4">
        <h4>Título</h4>
        <?php $style="style='width: 150px; heigth:140px;'" ;?>
        <?= add_image ('image.jpg','icons',$style) ?> 
        <p>hashdasdasdsadasdsadasdsadasdsakdnsfnsdfjndsjgndsgnsn
           gnghashdasdasdsadasdsadasdsadasdsakdnsfnsdfjndsjgndsg
           nsngngshashdasdasdsadasdsadasdsadasdsakdnsfnsdfjndsjg
           ndsgnsngngssdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfn
           dsfnsdsdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfndsfns
           sdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfndsfnsdfddds
           sdasfffsfsdfndsnfsdnfjdfnsdjfsnjdfjndsjkfndsfnsdfddds
        </p>

        <a href="#" class="btn btn-primary">Butao-zinho</a>
    </article>


</section>
