<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= APP_NAME ?></title>
    <?php stylesheet_include_tag('/bootstrap/css/bootstrap.min.css', 'application.css'); ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
  <body>
    
    <div class="col-md-12">
       <nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <?= link_to ("/", "Hotel Campeão","class='navbar-brand'" ) ?>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
    <!--     
 <li class="<?= activeClass('/acomodacoes')?>"><?= link_to('/acomodacoes', 'Acomodações')?></li>
-->
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Acomodações<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><?= link_to('/acomodacoes/individual','Individual')?></li>
          <li><?= link_to('/acomodacoes/duplo','Duplo')?></li>
          <li><?= link_to('/acomodacoes/triplo','Triplo')?></li>
        </ul>
    </li>


      <li class="<?= activeClass('/sobre') ?>"><?= link_to ('/sobre', "Sobre") ?></li>
      <li><a href="#">Localização</a></li>
      <li class="<?= activeClass('/fale-conosco') ?>"><?= link_to('/fale-conosco', 'Fale Conosco') ?></li> 
      <?php if (@$this->currentUser()) {?>
      <li><?= link_to('/admin','Área Administrativa') ?></li>
      <li><?= link_to('/logout','Seja Bem Vindo(a) ' . $this->currentUser()->getName() . '| Logout')?></li>
      <?php } else {?>
      <li><?php $img = add_image('lock.gif','icons'); echo link_to('/login',$img . '  Area restrita') ;?></li> 
       <?php }?>
    </ul>
 </div><!-- /.navbar-collapse -->
</nav>
</div>

    <div class="container">

        <?php foreach(Flash::message() as $key => $value){ ?>
          <div class="alert alert-<?= $key ?> fade in">
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
             <?= $value ?>
          </div>
        <?php } ?>

        <?php require $view; ?>
    </div>

    <?php javascript_include_tag('jquery-1.10.2.min.js', '/bootstrap/js/bootstrap.min.js', 'application.js') ?>
    <script src='http://code.jquery.com/ui/1.10.3/jquery-ui.js' type='text/JavaScript'>    
    </script>

   
  </body>
</html>
