<?php foreach($result as $row) {?>
<article class="col-md-12">
    <dl>
        <dt>Remetente:</dt>
        <dd><?= $row['name'] ?></dd>

        <dt>E-mail:</dt>
        <dd><?= $row['email'] ?></dd>
        
        <dt>Criação:</dt>
        <dd><?= $row['created_at'] ?></dd>

        <dt>Content:</dt>
        <dd><?= $row['content'] ?></dd>
    </dl>
    
    
    <?= link_to($this->back(),'Voltar',"class='btn btn-primary'")?>
    <?= link_to("/admin/mensagens/deletar/{$row['id']}",'Deletar',"class='btn btn-danger'")?>
    </form> 
</article>
<?php }?>

