<table class="table">
    <tr>
        <?php foreach($fields as $field) {?>
            <?php if($field != 'id') {?>
            <td><?= $field ?></td>
            <?php }?>
        <?php }?>
    </tr>   

    <?php foreach($other as $values) {?>
    <tr>
        <?php foreach($values as $value) {?>
        <td><?= $value ?></td>
        <?php }?>    
        
        <td><?php include '_form.phtml' ;?></td>
   </tr>
    <?php }?>
</table>

