<section>
    <header>
        <h1>Área Administrativa</h1>
        
    </header>
<article>
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
            <li><?= link_to('/admin/cadastrar','Cadastrar')?></li>
            <li><?= link_to('/admin/hospedagens', 'Hospedagens')?></li>
            <li><?= link_to('/admin/reservas','Reservas')?></li>
            <li><a href="#">Relatórios</a></li>
            <li><?= link_to('/admin/mensagens','Mensagens')?></li>
        </ul>

    </div>

    <div class="col-md-9">
        <h4>Olá <?= $this->currentUser()->getName()?> , bem vindo a sua área administrativa, aqui você manda ;)</h4>
        <h5>No menu ao lado, estão algumas ações que você pode tomar</h5>
    </div>
</article>



</section>
