<section>
    <header>
        <h1>Área para Cadastro de Coisas</h1>
        
    </header>
<article>
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
            <li><?= link_to('/admin/cadastrar/tipo-de-quarto','Tipo de Quarto')?></li>
            <li><?= link_to('/admin/cadastrar/produto','Produto')?></li>
            <li><?= link_to('/admin/cadastrar/servico','Serviço')?></li>        
            <li><?= link_to('/admin/cadastrar/usuario','Usuário')?></li>
            <li><?= link_to('/admin/cadastrar/cliente','Cliente')?></li>
        </ul>

    </div>

    <div class="col-md-9">
            
        <?php include "forms/" ."$form" ;?>
    </div>
</article>

</section>
