<script>
$(function() {
    $( "#accordion" ).accordion();
  });
</script>

<h1>Página com informações sobre o Hotel</h1>

<div id="accordion">
    <h3>Diárias</h3>
    <div>
        <p>
            As diárias duram 24 horas , se iniciando no dia resevado às 12 horas 
            e se encerrando no dia seguinte ás 12 horas.

            
        </p>
        
       <table class="table">
          <caption>Valores dos Quartos</caption>

          <thead>
            <tr>
                <th></th>
                <th>Simples</th>
                <th>Com ar e Frigobar</th>
            </tr>

           <tbody>
            <tr>
                <td>Individual</td>
                <td>R$ 50,00</td>
                <td>R$ 65,00</td>
            </tr>
            <tr>
                <td>Duplo</td>
                <td>R$ 90,00</td>
                <td>R$ 110,00</td>

            </tr>           
             <tr>
                <td>Triplo</td>
                <td>R$ 120,00</td>
                <td></td>

            </tr>           

        </table> 
        
        <a href="#">+ Detalhes sobre os quartos</a>

    
        <p><abbr title="Observação">Obs:</abbr> Não é cobrada tarifa para uma criança de 5 anos ou menos, porém,
        para mais de uma criança será cobrada uma tarifa</a>
        
    </div>

    <h3>Reserva</h3>
    <div>
        <p>As reservas são feitas através do telefone: (42) 3036-0039 <br />
        ou pelo e-mail: hotelcampeao@hotmail.com </p>
    </div>

    <h3>Formas de Pagamento</h3>
    <div>
        <ul>
            <li>Á vista</li>
            <li>Cartão de Crédito</li>
            <li>Cartão de Débito</li>
            <li>Boleto</li>
            <li>Convenio</li>
        </ul>
        <p>Pagamento em até 15 dias</p>
    </div>

    <h3>Serviços</h3>
    <div>
        <ul>
            <li>Estacionamento</li>
            <li>Lavanderia</li>
            
        </ul>
        
    </div>





</div>
